CREATE TABLE customer (
    customer_id BIGINT       NOT NULL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL
);

-- "transaction" is a reserved word, hence the longer table name.
CREATE TABLE purchase_transaction (
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT         NOT NULL,
    amount           DECIMAL(12, 2) NOT NULL,
    transaction_date DATE           NOT NULL,
    description      VARCHAR(200),
    CONSTRAINT fk_transaction_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT ck_transaction_amount CHECK (amount > 0)
);

CREATE INDEX idx_transaction_customer_date ON purchase_transaction (customer_id, transaction_date);
